### ISSUE TITLE
Incomplete features

### ISSUE THREAD

**Issue by MichalNemec** [IshuPrabhakar/Heyy-chat-app#5]
Based on what can be seen in readme and on file https://github.com/IshuPrabhakar/Heyy-chat-app/blob/master/Heyy%20Frontend/lib/screens/chat/chat_screen.dart it does not have features its claiming.

**Comment by IshuPrabhakar** [comment]
> Based on what can be seen in readme and on file https://github.com/IshuPrabhakar/Heyy-chat-app/blob/master/Heyy%20Frontend/lib/screens/chat/chat_screen.dart it does not have features its claiming.

It is not completely open source.
